name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read

jobs:
  build-linux-ubuntu:
    runs-on: tpi-ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install ML-KAPS
      run: pip install .
    - name: Test with pytest
      run: pytest
